# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 260d06eb4b72f197f64b5ca227b01d4e5ed913ec5e0e2a55402676ac254d6ee5c6b486cafb51ebf71b65f53fea52b17f694ec18a2842d82e869c5618954505fa

test:
  secret_key_base: ecf65693d170738da0a1832778ac7ef769950007dd19a046c595fdfedfd1c0af6e545bb4d509de3445b2eae19727c3cc8f8b2c91200f3291d62d437a3b89062c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
